[project]
name = "repl-nix-carpicsorterai-1"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask-bcrypt>=1.0.1",
    "flask-login>=0.6.3",
    "pandas>=2.2.3",
    "pillow>=10.4.0",
    "psycopg2-binary>=2.9.10",
    "streamlit>=1.39.0",
    "tensorflow>=2.17.0",
]
