[server]
headless = true
address = "0.0.0.0"
port = 5000
maxUploadSize = 1000
enableXsrfProtection = false
enableCORS = false
maxMessageSize = 200

[logger]
level = "error"
messageFormat = "%(asctime)s - %(message)s"

[theme]
base = "light"

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false
installTracer = false
fixMatplotlib = false

[client]
showErrorDetails = false
toolbarMode = "minimal"
